# Cloudflare Pages 配置
name = "line-bot-pusher"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages 配置
pages_build_output_dir = "deploy"

# 環境變數
[env.production.vars]
NODE_ENV = "production"
PORT = "8787"
MAX_PUSH_RATE = "1000"
MAX_MESSAGE_LENGTH = "2000"
LOG_LEVEL = "info"

# KV 存儲 (暫時移除，主要使用 D1)
# [[env.production.kv_namespaces]]
# binding = "LINE_BOT_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 資料庫 (Cloudflare 的 SQLite)
[[env.production.d1_databases]]
binding = "LINE_BOT_DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

[[env.production.d1_databases]]
binding = "DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

# 全域 D1 資料庫配置
[[d1_databases]]
binding = "DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

# 預覽環境 (對應 Pages 的 preview)
[env.preview.vars]
NODE_ENV = "preview"
PORT = "8787"
MAX_PUSH_RATE = "500"
MAX_MESSAGE_LENGTH = "2000"
LOG_LEVEL = "debug"