# Cloudflare Pages 配置
name = "line-bot-pusher"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages 配置
# pages_build_output_dir = "deploy"  # 註解掉，使用根目錄

# 默認環境變數 (所有分支都會使用)
[vars]
NODE_ENV = "development"
PORT = "8787"
MAX_PUSH_RATE = "500"
MAX_MESSAGE_LENGTH = "2000"
LOG_LEVEL = "debug"

# 環境變數
[env.production.vars]
NODE_ENV = "production"
PORT = "8787"
MAX_PUSH_RATE = "1000"
MAX_MESSAGE_LENGTH = "2000"
LOG_LEVEL = "info"

# R2 存儲配置 (生產環境)
[[env.production.r2_buckets]]
bucket_name = "line-bot-images"
binding = "R2_IMAGES"

# KV 存儲 (暫時移除，主要使用 D1)
# [[env.production.kv_namespaces]]
# binding = "LINE_BOT_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# D1 資料庫 (Cloudflare 的 SQLite)
[[env.production.d1_databases]]
binding = "LINE_BOT_DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

[[env.production.d1_databases]]
binding = "DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

# 全域 D1 資料庫配置
[[d1_databases]]
binding = "DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

[[d1_databases]]
binding = "LINE_BOT_DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

# R2 存儲配置
[[r2_buckets]]
bucket_name = "line-bot-images"
binding = "R2_IMAGES"

# 預覽環境 (對應 Pages 的 preview - 所有非 main 分支)
[env.preview.vars]
NODE_ENV = "preview"
PORT = "8787"
MAX_PUSH_RATE = "500"
MAX_MESSAGE_LENGTH = "2000"
LOG_LEVEL = "debug"

# 預覽環境使用相同的資料庫
[[env.preview.d1_databases]]
binding = "LINE_BOT_DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

# 預覽環境使用相同的 R2 存儲
[[env.preview.r2_buckets]]
bucket_name = "line-bot-images"
binding = "R2_IMAGES"

# 開發環境 (對應 develop 分支)
[env.develop.vars]
NODE_ENV = "development"
PORT = "8787"
MAX_PUSH_RATE = "500"
MAX_MESSAGE_LENGTH = "2000"
LOG_LEVEL = "debug"

# 開發環境使用相同的資料庫
[[env.develop.d1_databases]]
binding = "LINE_BOT_DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

[[env.develop.d1_databases]]
binding = "DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

# 開發環境使用相同的 R2 存儲
[[env.develop.r2_buckets]]
bucket_name = "line-bot-images"
binding = "R2_IMAGES"

# 嘗試為所有 preview/branch 環境配置資料庫
[env.development.vars]
NODE_ENV = "development"

[[env.development.d1_databases]]
binding = "DB"
database_name = "line-bot-database"  
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

[[env.development.d1_databases]]
binding = "LINE_BOT_DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

# 額外的分支環境配置
[env.staging.vars]
NODE_ENV = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"

[[env.staging.d1_databases]]
binding = "LINE_BOT_DB"
database_name = "line-bot-database"
database_id = "1e5d0326-41d7-4621-864d-b0c1ed49adcd"