# Cloudflare Workers 配置
name = "line-bot-pusher"
compatibility_date = "2024-08-23"

# Worker 類型
main = "src/worker.js"

# 環境變數
[env.production.vars]
NODE_ENV = "production"
PORT = "8787"
MAX_PUSH_RATE = "1000"
MAX_MESSAGE_LENGTH = "2000"
LOG_LEVEL = "info"

# KV 存儲 (用於存儲群組和模板資料)
[[env.production.kv_namespaces]]
binding = "LINE_BOT_KV"
id = ""
preview_id = ""

# D1 資料庫 (Cloudflare 的 SQLite)
[[env.production.d1_databases]]
binding = "LINE_BOT_DB"
database_name = "line-bot-database"
database_id = ""

# 開發環境
[env.development.vars]
NODE_ENV = "development"
PORT = "3000"
MAX_PUSH_RATE = "500"
MAX_MESSAGE_LENGTH = "2000"
LOG_LEVEL = "debug"